# Generated by Django 3.2.23 on 2024-02-15 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_no', models.CharField(max_length=500)),
                ('rank', models.CharField(max_length=500)),
                ('full_names', models.CharField(max_length=500)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('formal_educ', models.CharField(max_length=500)),
                ('courses_attnd', models.CharField(max_length=500)),
                ('appointment', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=500)),
                ('county', models.CharField(max_length=500)),
                ('sub_county', models.CharField(max_length=500)),
                ('parish', models.CharField(max_length=500)),
                ('vilage', models.CharField(max_length=500)),
                ('soldier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sdrTest.soldier')),
            ],
        ),
    ]
